// Generated by Wrangler by running `wrangler types`

interface Env {
	BOT_ID: string;
	OWNER_ID: string;
	CLIENT_EMAIL: string;
	CLIENT_ID: string;
	CLIENT_X509_CERT_URL: string;
	TELEGRAM_API: string;
	PROJECT_ID: string;
	PRIVATE_KEY_ID: string;
	PRIVATE_KEY: string;
	SUPABASE_URL: string;
	SUPABASE_KEY: string;
	AI: Ai;
}
